alert('Welcom hm1');
alert('У меня есть 4 переменные вот такого типа');
var stringString = 'abc';
var namberNamber = 22;
var bigIntNamber = 22222222222222222222n;
var booleonUser  = true;
alert(stringString );
alert(typeof stringString);
alert(namberNamber);
alert(typeof namberNamber);
alert(bigIntNamber);
alert(typeof bigIntNamber);
alert(booleonUser);
alert(typeof booleonUser);
var answerUser = confirm('Понравилось?');
console.log(answerUser);
